# fix this relative to include/
# or use absolute path to the GRASS source code
MODULE_TOPDIR = ../../..

PGM = r.solpos

LIBES = $(GISLIB) $(GPROJLIB)
DEPENDENCIES = $(GISDEP)
EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

#r.solpos: main-r.solpos.c solpos00.c cstars-solpos.c cstars-projection.c timezone.c





